collections:
  - name: amazon.aws
    version: ">=9.0.0"
  - name: azure.azcollection
    version: ">=4.0.0"
  - name: google.cloud
    version: ">=1.14.0"
  - name: ansible.posix
    version: ">=2.2.2"
  - name: ctrliq.ascender
    version: "25.6.2"
  - name: community.docker
    version: ">=5.1.0"
  - name: community.general
    version: ">=12.5.0"
  - name: kubernetes.core
    version: ">=6.2.0"
  - name: community.aws
    version: ">=11.1.0"
