--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: {{ EKS_CLUSTER_NAME }}
  region: {{ EKS_CLUSTER_REGION }}
  version: "{{ EKS_K8S_VERSION }}"
vpc:
  cidr: {{ EKS_CLUSTER_CIDR }}
  hostnameType: resource-name
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
nodeGroups:
- name: ascender-nodes
  instanceType: {{ EKS_INSTANCE_TYPE }}
  # instanceName: custom-node-name
  minSize: {{ EKS_MIN_WORKER_NODES }}
  maxSize: {{ EKS_MAX_WORKER_NODES }}
  desiredCapacity: {{ EKS_NUM_WORKER_NODES }}
  volumeSize: {{ EKS_WORKER_VOLUME_SIZE }}
  tags:
    nodegroup-role: worker
iam:
  withOIDC: true
addons:
- name: kube-proxy
- name: coredns
- name: vpc-cni
- name: aws-ebs-csi-driver
  version: {{ EKS_EBS_CSI_DRIVER_VERSION }}
  attachPolicyARNs:
  - {{ ebs_scsi_driver_policy_arn }}