---
{% set eks_cluster_normalized = eks_cluster.cluster if (eks_cluster is mapping and 'cluster' in eks_cluster) else eks_cluster %}
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    apiServerEndpoint: "{{ eks_cluster_normalized.endpoint }}"
    certificateAuthority: "{{ eks_cluster_normalized.certificate_authority.data }}"
    cidr: 172.20.0.0/16
    name: "{{ EKS_CLUSTER_NAME }}"
  kubelet:
    config:
#      maxPods: 35
      clusterDNS:
      - 172.20.0.10
    flags:
    - "--node-labels=eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup={{ EKS_CLUSTER_NAME }}-nodes"