---
  ### Minimal example for installing a standalone k3s node      ###
  ### For more configuration settings, please see the docs      ###
  ### copy this file to custom.config.yml and run the installer ###
  #
  # ---Kubernetes-specific variables---

    # This variable specificies which Kubernetes platform Ascender and its components will be installed on.
k8s_platform: k3s

    # Determines whether to use HTTP or HTTPS for Ascender and Ledger.
    # If set to https, you MUST provide certificate/key options for the Installer to use.
    # options include http and https
k8s_lb_protocol: http 

    # Routable IP address for the K8s API Server
    # (This could be a Load Balancer if using 3 K8s control nodes)
kubeapi_server_ip: "127.0.0.1"

    # This value being set to "true" means that some work needs to be done to set up a
    # cluster before proceeding. Here is ther behavior for different values of k8s_platforms:
    # k3s: A single-node k3s cluster will be set up on the inventory server
    #      named "ascender_host"
kube_install: true

    # Indictates whether or not the kubeconfig file needs to be downloaded to the Ansible controller
download_kubeconfig: true

  # ---k3s variables---

    # IP address for the K3s Master/Worker node
    # Required for local DNS and k3s install
    # This IP Address must be reachable by the server from which this installer is running
k3s_master_node_ip: "127.0.0.1"

    # ---Local artifact variables---

    # TLS Certificate file, required when deploying HTTPS in K3s
tls_crt_path: "~/ascender.crt"

    # TLS Private Key file, required when deploying HTTPS in K3s
tls_key_path: "~/ascender.key"

    # Set to false if using an external DNS server for resolution
    # Set to true if not
use_etc_hosts: true

  # ---Ascender install variables---

    # DNS resolvable hostname for Ascender service. This is required for install.
ASCENDER_HOSTNAME: ascender.example.com

    # Administrator username for Ascender
ASCENDER_ADMIN_USER: admin

    # Administrator password for Ascender
ASCENDER_ADMIN_PASSWORD: "myadminpassword"

  # ---Ledger install variables---

    # Determines whether or not Ledger will be installed
LEDGER_INSTALL: true

    # DNS resolvable hostname for Ledger service. This is required for install.
LEDGER_HOSTNAME: ledger.example.com

    # Admin password for Ledger (the username is admin by default)
LEDGER_ADMIN_PASSWORD: "myadminpassword"

    # Password for Ledger database
LEDGER_DB_PASSWORD: "mydbpassword"

