---
# ---Kubernetes-specific variables---

# This variable specificies which Kubernetes platform Ascender and its components will be installed on.
k8s_platform: eks # Options include k3s, eks and dkp, with more to come.

# Determines whether to use HTTP or HTTPS for Ascender.
# If set to https, you MUST provide certificate/key options for the Installer to use.
k8s_lb_protocol: http #options include http and https

# ---Local artifact variables---

# TLS Certificate file, required when deploying HTTPS in K3s
tls_crt_path: "~/ascender.crt"

# TLS Private Key file, required when deploying HTTPS in K3s
tls_key_path: "~/ascender.key"

# Set to false if using an external DNS server for resolution
# Set to true if not
use_etc_hosts: true

# A directory in which to place both temporary artifacts
# and timestamped Kubernetes Manifests to make Ascender easy
# to uninstall
tmp_dir: "{{ playbook_dir }}/../ascender_install_artifacts"

# ---Ascender install variables---

# DNS resolvable hostname for Ascender service. This is required for install.
ASCENDER_HOSTNAME: ascender.example.com

# The domain name for all components; required when k8s_platorm=="eks"
ASCENDER_DOMAIN: example.com

# k8s namespace for Ascender k8s objects
ASCENDER_NAMESPACE: ascender

# Administrator username for Ascender
ASCENDER_ADMIN_USER: admin

# Administrator password for Ascender
ASCENDER_ADMIN_PASSWORD: "myadminpassword"

# The OCI container image for Ascender
ASCENDER_IMAGE: ghcr.io/ctrliq/ascender

# The image tag indicating the version of Ascender you wish to install
ASCENDER_VERSION: 25.3.6

# The version of the AWX Operator used to install Ascender and its components
ASCENDER_OPERATOR_VERSION: 2.19.5

# Determines whether to keep the secrets required to encrypt within Ascender (important when backing up)
ascender_garbage_collect_secrets: true

# # External PostgreSQL ip or url resolvable by the cluster
# ASCENDER_PGSQL_HOST: "ascenderpghost.example.com" 

# # External PostgreSQL port, this usually defaults to 5432
# ASCENDER_PGSQL_PORT: 5432 

# # External PostgreSQL username
# ASCENDER_PGSQL_USER: ascender

# # External PostgreSQL password
# NOTE: Do NOT use the special characters in the postgres password (Django requirement)
# ASCENDER_PGSQL_PWD: mypgadminpassword

# # External PostgreSQL database name used for Ascender (this DB must exist)
# ASCENDER_PGSQL_DB: ascenderdb


### All of these options are unnecessary to change, but will allow you to tweak your Ascender deployment if you choose to change them
ascender_replicas: 1
ascender_image_pull_policy: Always
