apiVersion: v1
kind: Secret
metadata:
  name: ciq-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ {
    "auths": {
      CIQ_REGISTRY.BASE: {
        "auth": (CIQ_REGISTRY.USERNAME ~ ":" ~ CIQ_REGISTRY.PASSWORD) | b64encode
      }
    }
  } | to_json | b64encode }}
