- name: Get AWS account ID
  amazon.aws.aws_caller_info:
  register: account_info

- name: Set account ID
  set_fact:
    aws_account_id: "{{ account_info.account }}"

- name: Get available availability zones
  amazon.aws.aws_az_info :
    region: "{{ EKS_CLUSTER_REGION }}"
    filters:
      state: available
  register: az_info

- name: Set availability zones
  set_fact:
    availability_zones: "{{ az_info.availability_zones | map(attribute='zone_name') | list }}"

- name: Get Amazon AMI
  amazon.aws.ec2_ami_info:
    region: "{{ EKS_CLUSTER_REGION }}"
    owners:
      - "amazon"
    filters:
      name: "amazon-eks-node-al2023-x86_64-standard-{{ EKS_K8S_VERSION }}-*"
      state: "available"
  register: ami_info

- name: Set Amazon AMI ID
  set_fact:
    amazon_ami_id: "{{ (ami_info.images | sort(attribute='creation_date', reverse=true) | first).image_id }}"

- name: Create VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ EKS_CLUSTER_NAME }}-vpc"
    region: "{{ EKS_CLUSTER_REGION }}"
    cidr_block: "{{ EKS_CLUSTER_CIDR }}"
    dns_hostnames: true
    dns_support: true
    state: present
  register: vpc

- debug: 
    msg: "{{ EKS_CLUSTER_CIDR | ansible.utils.ipsubnet(26, count) }}"
  loop: "{{ range(0, EKS_NUM_SUBNETS) | list }}"
  loop_control:
    loop_var: count

- name: Set subnet base tags
  set_fact:
    subnet_base_tags: "{{ {'kubernetes.io/cluster/' + EKS_CLUSTER_NAME: 'owned', 'kubernetes.io/role/' + ('elb' if EKS_PUBLIC else 'internal-elb'): '1'} }}"

- name: Create private subnets
  amazon.aws.ec2_vpc_subnet:
    region: "{{ EKS_CLUSTER_REGION }}"
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ EKS_CLUSTER_CIDR | ansible.utils.ipsubnet(EKS_SUBNET_SIZE, count) }}"
    az: "{{ availability_zones[count] }}"
    state: present
    map_public: "{{ true if EKS_PUBLIC else false }}" # If set to false, EKS nodes will fail to provision
    tags: "{{ subnet_base_tags | combine({'Name': EKS_CLUSTER_NAME + ('-public-subnet-' if EKS_PUBLIC else '-private-subnet-') + (count | string)}) }}"
  
  loop: "{{ range(0, EKS_NUM_SUBNETS) | list }}"
  loop_control:
    loop_var: count
  register: subnets

- name: Create internet gateway
  amazon.aws.ec2_vpc_igw:
    region: "{{ EKS_CLUSTER_REGION }}"
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    tags:
      Name: "{{ EKS_CLUSTER_NAME }}-igw"
  register: igw
  when: internet_gateway | default(true)

- name: Add route to internet gateway
  amazon.aws.ec2_vpc_route_table:
    region: "{{ EKS_CLUSTER_REGION }}"
    vpc_id: "{{ vpc.vpc.id }}"
    tags:
      Name: "{{ EKS_CLUSTER_NAME }}-route-table"
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ igw.gateway_id }}"
    subnets: "{{ subnets.results | map(attribute='subnet.id') | list }}"
  when: internet_gateway | default(true)

- name: Add route
  amazon.aws.ec2_vpc_route_table:
    region: "{{ EKS_CLUSTER_REGION }}"
    vpc_id: "{{ vpc.vpc.id }}"
    tags:
      Name: "{{ EKS_CLUSTER_NAME }}-route-table"
    subnets: "{{ subnets.results | map(attribute='subnet.id') | list }}"
  when: not (internet_gateway | default(true))

- name: Create security group for EKS nodes
  amazon.aws.ec2_security_group:
    name: "{{ EKS_CLUSTER_NAME }}-node-sg"
    description: "Security group for EKS node cluster communication"
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ EKS_CLUSTER_REGION }}"
    rules:
      - proto: tcp
        from_port: 0
        to_port: 65535
        cidr_ip: "0.0.0.0/0"
        rule_desc: "Allow all traffic from cluster VPC"
      - proto: tcp
        from_port: 0
        to_port: 65535
        cidr_ip: "{{ EKS_CLUSTER_CIDR }}"
        rule_desc: "Allow node-to-node communication"
      - proto: udp
        from_port: 0
        to_port: 65535
        cidr_ip: "{{ EKS_CLUSTER_CIDR }}"
        rule_desc: "Allow node-to-node communication (UDP)"
    rules_egress:
      - proto: -1
        cidr_ip: "0.0.0.0/0"
    state: present
  register: security_group

- set_fact:
    policy_doc: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }

- name: Attach EKS cluster policy
  amazon.aws.iam_role:
    name: "{{ EKS_CLUSTER_NAME }}-cluster-role"
    assume_role_policy_document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    managed_policies:
      - "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
      - "arn:aws:iam::aws:policy/AmazonEKSLoadBalancingPolicy"
      - "arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess"

- name: Create Public EKS cluster
  community.aws.eks_cluster:
    name: "{{ EKS_CLUSTER_NAME }}"
    version: "{{ EKS_K8S_VERSION }}"
    role_arn: "arn:aws:iam::{{ aws_account_id }}:role/{{ EKS_CLUSTER_NAME }}-cluster-role"
    security_groups:
      - "{{ security_group.group_id }}"
    subnets: "{{ subnets.results | map(attribute='subnet.id') | list }}"
    state: present
    region: "{{ EKS_CLUSTER_REGION }}"
    wait: true
  register: eks_cluster
  when: EKS_PUBLIC | bool

- name: Create Private EKS Cluster
  ansible.builtin.shell: >
    eksctl create cluster
    --name="{{ EKS_CLUSTER_NAME }}"
    --region="{{ EKS_CLUSTER_REGION }}"
    --version="{{ EKS_K8S_VERSION }}"
    --authenticator-role-arn="arn:aws:iam::{{ aws_account_id }}:role/{{ EKS_CLUSTER_NAME }}-cluster-role"
    --vpc-private-subnets={{ subnets.results | map(attribute='subnet.id') | join(',') }}
    --node-private-networking
    --managed
  when: not (EKS_PUBLIC | bool)

- name: Create IAM role for EKS node group
  amazon.aws.iam_role:
    name: "{{ EKS_CLUSTER_NAME }}-node-group-role"
    assume_role_policy_document: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Principal": {
                      "Service": "ec2.amazonaws.com"
                  },
                  "Action": "sts:AssumeRole"
              },
              {
                  "Effect": "Allow",
                  "Principal": {
                      "Service": "eks.amazonaws.com"
                  },
                  "Action": "sts:AssumeRole"
              },
              {
                  "Effect": "Allow",
                  "Principal": {
                      "Service": "ecs.amazonaws.com"
                  },
                  "Action": "sts:AssumeRole"
              }
          ]
      }
    state: present
    managed_policies:
      - "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
      - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      - "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
      - "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
      - "arn:aws:iam::aws:policy/AmazonEKSLoadBalancingPolicy"
      - "arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess"

- name: Create launch template for node group
  amazon.aws.ec2_launch_template:
    name: "eks-node-launch-template"
    image_id: "{{ amazon_ami_id }}"
    instance_type: "{{ EKS_INSTANCE_TYPE }}"
    region: "{{ EKS_CLUSTER_REGION }}"
    user_data: "{{ lookup('template', 'templates/eks/NodeConfig.yml') | b64encode }}"
    state: present
  register: launch_template

- name: Create EKS node group
  community.aws.eks_nodegroup:
    name: "{{ EKS_CLUSTER_NAME }}-nodes"
    cluster_name: "{{ EKS_CLUSTER_NAME }}"
    subnets: "{{ subnets.results | map(attribute='subnet.id') | list }}"
    node_role: "arn:aws:iam::{{ aws_account_id }}:role/{{ EKS_CLUSTER_NAME }}-node-group-role"
    scaling_config:
      min_size: "{{ num_min_nodes | default(1) }}"
      max_size: "{{ num_max_nodes | default(3) }}"
      desired_size: "{{ EKS_NUM_WORKER_NODES }}"
    launch_template:
      id: "{{ launch_template.template.launch_template_id }}"
      version: "$Latest"
    region: "{{ EKS_CLUSTER_REGION }}"
    state: present
    wait: true
