# kubectl edit -n kube-system configmap/aws-auth

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<aws account number>:role/eksctl-<EKS-CLUSTER-NAME>-nodegr-NodeInstanceRole-XXXXXXXX
      username: system:node:{{EC2PrivateDNSName}}
  ###### INCLUDE THIS SNIPPET ######
  mapUsers: |
    - userarn: arn:aws:iam::<aws account number>:user/<EKS_USER>
      username: <EKS_USER>
      groups:
      - system:masters
  ###### END SNIPPET ######
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system