--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ascender-eks-cluster
  region: us-east-1
  version: "1.28"
vpc:
  cidr: "10.10.0.0/16"
  hostnameType: resource-name
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
nodeGroups:
- name: ascender-nodes
  instanceType: t3.large
  # instanceName: custom-node-name
  minSize: 2
  maxSize: 6
  desiredCapacity: 4
  volumeSize: 100
  ssh: 
    allow: true
    publicKeyName: mford-useast-1-key #Existing AWS Public Key
  tags:
    nodegroup-role: worker
addons:
- name: kube-proxy
- name: coredns
- name: vpc-cni
