- name: Retrieve the current time in order to timestamp files
  ansible.builtin.setup:
    gather_subset:
     - date_time

- name: Query for aws account number
  amazon.aws.aws_caller_info:
  register: caller_info
  no_log: true

- name: Create Ascender Create Policy JSON file
  ansible.builtin.template:
    src: templates/eks/iam_policies/ascenderinstallpermissions_all.json
    dest: "{{ playbook_dir }}/../ascender_install_artifacts/ascender_install_permissions.json.{{ ansible_date_time.iso8601_basic_short }}"