---
# This variable specificies which Kubernetes platform Ascender and its components will be installed on.
k8s_platform: gke
# Determines whether to use HTTP or HTTPS for Ascender.
# If set to https, you MUST provide certificate/key options for the Installer to use.
k8s_lb_protocol: http
# Determines whether to use Google Cloud DNS Domain Management (which is automated)
# Or a third-party service (e.g., Cloudflare, GoDaddy, etc.)
# If this value is set to false, you will have to manually set an A record for
# {{ASCENDER_HOSTNAME }} to point to the Google Cloud
# Loadbalancers
USE_GOOGLE_DNS: true
# TLS Certificate file location on the local installing machine
tls_crt_path: "/home/rocky/ascender.crt"
# TLS Private Key file location on the local installing machine
tls_key_path: "/home/rocky/ascender.key"
# A directory in which to place both temporary artifacts
# and timestamped Kubernetes Manifests to make Ascender easy
# to uninstall
tmp_dir: "{{ playbook_dir}}/../ascender_install_artifacts"
# DNS resolvable hostname for Ascender service. This is required for install.
ASCENDER_HOSTNAME: ascender.example.com
# DNS domain for Ascender service. This is required when hosting on cloud services.
ASCENDER_DOMAIN: example.com
# In Google Cloud DNS the name of an existing hosted DNS zone for your DNS record.
GOOGLE_DNS_MANAGED_ZONE: "example-com"
# Namespace for Ascender Kubernetes objects
ASCENDER_NAMESPACE: ascender
# Administrator username for Ascender
ASCENDER_ADMIN_USER: admin
# Administrator password for Ascender
ASCENDER_ADMIN_PASSWORD: "myadminpassword"
# The image tag indicating the version of Ascender you wish to install
ASCENDER_VERSION: 25.3.6
# The version of the AWX Operator used to install Ascender and its components
ASCENDER_OPERATOR_VERSION: 2.19.5
# Determines whether to keep the secrets required to encrypt within Ascender (important when backing up)
ascender_garbage_collect_secrets: false
# External PostgreSQL database name used for Ascender (this DB must exist)
ascender_replicas: 1
# Boolean indicating whether to add standard playbooks into Ascender after installation
ascender_setup_playbooks: false
