- name: Set the Ascender URL for HTTPS
  ansible.builtin.set_fact:
      ascender_ip: "{{ ASCENDER_HOSTNAME }}"
      ascender_port: 443
  when: k8s_lb_protocol == "https"

- name: Set the Ascender URL for HTTP
  ansible.builtin.set_fact:
      ascender_ip: "{{ ASCENDER_HOSTNAME }}"
      ascender_port: 80
  when: k8s_lb_protocol == "http"

- ansible.builtin.debug:
    msg: "The Ascender API endpoint is {{ k8s_lb_protocol }}://{{ ascender_ip }}:{{ ascender_port }}/api/v2/ping/"
    
- name: Wait until Ascender API is Up
  ansible.builtin.uri:
    url: "{{ k8s_lb_protocol }}://{{ ascender_ip }}:{{ ascender_port }}/api/v2/ping/"
    return_content: yes
    validate_certs: no
    status_code:
      - 200
  until: uri_output.status == 200
  retries: 200
  delay: 10
  register: uri_output