- name: Create Project - {{ project.name }}
  awx.awx.project:
    controller_host: "{{ k8s_lb_protocol }}://{{ ascender_ip }}:{{ ascender_port }}"
    controller_username: "{{ ASCENDER_ADMIN_USER }}"
    controller_password: "{{ ASCENDER_ADMIN_PASSWORD }}"
    name: "{{ project.name }}"
    description: "{{ project.description }}"
    organization: Default
    scm_type: "{{ project.scm_type }}"
    scm_url: "{{ project.scm_url }}"
    scm_update_on_launch: "{{ project.scm_update_on_launch | default(omit) }}"
    validate_certs: false
  register: result
  until: result is succeeded
  retries: 20
  delay: 5


