---
    # This variable specifies which Kubernetes platform Ascender and its components will be installed on.
k8s_platform: ocp

    # Determines whether to use HTTP or HTTPS for Ascender.
    # If set to https, you MUST provide certificate/key options for the Installer to use.
    # options include http and https
k8s_lb_protocol: http

    # TLS Certificate file, required when deploying HTTPS
tls_crt_path: "~/ascender.crt"

    # TLS Private Key file, required when deploying HTTPS
tls_key_path: "~/ascender.key"

    # Set to false if using an external DNS server for resolution
    # Set to true if not
use_etc_hosts: true

    # DNS resolvable hostname for Ascender service. This is required for install.
ASCENDER_HOSTNAME: ascender.example.com

    # Administrator password for Ascender
ASCENDER_ADMIN_PASSWORD: "myadminpassword"

    # Setup extra demo playbooks after installation
ascender_setup_playbooks: true
