apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: ascender-restore-{{ ansible_date_time.date }}-{{ ansible_date_time.epoch }}
  namespace: {{ ASCENDER_NAMESPACE }}
spec:
  deployment_name: ascender-app
  backup_name: 