# Copyright (c) 2023, Ctrl IQ, Inc. All rights reserved.

- hosts: localhost
  gather_facts: no
  become: false

  vars_files:
    - ["../custom.config.yml", "../default.config.yml"]

  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"
    NAMESPACE: "{{ ASCENDER_NAMESPACE }}"
    PATH: "/usr/local/bin:{{ lookup('env', 'PATH') }}" #required as the aws cli lives at /usr/local/bin/aws
  
  tasks: 

    - name: "Apply minimum permissions to install Ascender in a Kubernetes cluster of type {{ k8s_platform }}"
      ansible.builtin.include_role:
        name: apply_permissions
        tasks_from: "apply_permissions_{{ k8s_platform }}"