- hosts: localhost
  gather_facts: no
  connection: local
  become: false

  vars_files:
    - ["custom.config.yml", "default.config.yml"]

  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"
    NAMESPACE: "{{ LEDGER_NAMESPACE }}"
    PATH: "/usr/local/bin:{{ lookup('env', 'PATH') }}" #required as the aws cli lives at /usr/local/bin/aws

  tasks:

    - name: "Run ascender_install role for {{ k8s_platform }}"
      ansible.builtin.include_role:
        name: ascender_cleanup
        tasks_from: "ascender_cleanup_{{ k8s_platform }}"
