apiVersion: v1
data:
  admin-password:  {{ LEDGER_PASSWORD | b64encode }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: admin-password
  name: admin-password
type: Opaque
---
apiVersion: v1
data:
  db-ledger-password: {{ LEDGER_DB_PASSWORD | b64encode }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-ledger-password
  name: db-ledger-password
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: db
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: parser
  name: parser
spec:
  type: NodePort
  ports:
  - name: parser-port
    port: 5000
    targetPort: 5000
    nodePort: {{ LEDGER_PARSER_NODEPORT | default(omit, true) }}
    protocol: TCP
  selector:
    io.kompose.service: parser
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web-svc
  name: web-svc
spec:
  type: NodePort
  ports:
  - name: web-port
    port: 80
    nodePort: {{ LEDGER_WEB_NODEPORT | default(omit, true) }}
    targetPort: 80
  selector:
    io.kompose.service: web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-data
  name: mysql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10240Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/ledger-default: "true"
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: ADMIN_USER
          value: admin
        - name: MYSQL_LEDGER_PASSWORD
          value: /run/secrets/db-ledger-password
        - name: admin-password
          value: /run/secrets/admin-password
        image: {{ LEDGER_DB_IMAGE }}:{{ LEDGER_VERSION }}
        imagePullPolicy: Always
        name: db
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /run/secrets/db-ledger-password
          name: db-ledger-password
        - mountPath: /run/secrets/admin-password
          name: admin-password
        - mountPath: /var/lib/mysql
          name: mysql-data
      restartPolicy: Always
      volumes:
      - name: db-ledger-password
        secret:
          items:
          - key: db-ledger-password
            path: db-ledger-password
          secretName: db-ledger-password
      - name: admin-password
        secret:
          items:
          - key: admin-password
            path: admin-password
          secretName: admin-password
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: parser
  name: parser
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: parser
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/ledger-default: "true"
        io.kompose.service: parser
    spec:
      containers:
      - env:
        - name: MYSQL_LEDGER_PASSWORD
          value: /run/secrets/db-ledger-password
        image: {{ LEDGER_PARSER_IMAGE }}:{{ LEDGER_VERSION }}
        imagePullPolicy: Always
        name: parser
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /run/secrets/db-ledger-password
          name: db-ledger-password
      restartPolicy: Always
      volumes:
      - name: db-ledger-password
        secret:
          items:
          - key: db-ledger-password
            path: db-ledger-password
          secretName: db-ledger-password
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/ledger-default: "true"
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: MYSQL_LEDGER_PASSWORD
          value: /run/secrets/db-ledger-password
        image: {{ LEDGER_WEB_IMAGE }}:{{ LEDGER_VERSION }}
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /run/secrets/db-ledger-password
          name: db-ledger-password
      restartPolicy: Always
      volumes:
      - name: db-ledger-password
        secret:
          items:
          - key: db-ledger-password
            path: db-ledger-password
          secretName: db-ledger-password
status: {}
