apiVersion: v1
kind: Secret
metadata:
  name: ledger-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ {
    "auths": {
      LEDGER_REGISTRY.BASE: {
        "auth": (LEDGER_REGISTRY.USERNAME ~ ":" ~ LEDGER_REGISTRY.PASSWORD) | b64encode
      }
    }
  } | to_json | b64encode }}
