---
# This variable specificies which Kubernetes platform Ascender and its components will be installed on.
k8s_platform: aks
# Determines whether to use HTTP or HTTPS for Ascender.
# If set to https, you MUST provide certificate/key options for the Installer to use.
k8s_lb_protocol: https
# Determines whether to use Azure DNS Domain Management (which is automated)
# Or a third-party service (e.g., Cloudflare, GoDaddy, etc.)
# If this value is set to false, you will have to manually set an A record for
# {{ASCENDER_HOSTNAME }} to point to the Azure
# Loadbalancers
USE_AZURE_DNS: true
# TLS Certificate file location on the local installing machine
tls_crt_path: "/home/rocky/ascender.crt"
# TLS Private Key file location on the local installing machine
tls_key_path: "/home/rocky/ascender.key"
# CA Bundle that contains both your CA Cert and other external CA bundles
# Such as the ones located at /etc/ssl/certs/ca-bundle.crt
# To create: "cat /etc/ssl/certs/ca-bundle.crt  ~/myca.crt > ~/my-ca-bundle.crt"
#custom_cacert_bundle: "~/my-ca-bundle.crt"
# LDAP CA Cert
#custom_ldap_cacert: "~/my-ldap-ca.crt"
# A directory in which to place both temporary artifacts
# and timestamped Kubernetes Manifests to make Ascender easy
# to uninstall
tmp_dir: "{{ playbook_dir}}/../ascender_install_artifacts"
# DNS resolvable hostname for Ascender service. This is required for install.
ASCENDER_HOSTNAME: ascender.example.com
# DNS domain for Ascender service. This is required when hosting on cloud services.
ASCENDER_DOMAIN: example.com
# Namespace for Ascender Kubernetes objects
ASCENDER_NAMESPACE: ascender
# Administrator username for Ascender
ASCENDER_ADMIN_USER: admin
# Administrator password for Ascender
ASCENDER_ADMIN_PASSWORD: "myadminpassword"
# The image tag indicating the version of Ascender you wish to install
ASCENDER_VERSION: 25.3.6
# The version of the AWX Operator used to install Ascender and its components
ASCENDER_OPERATOR_VERSION: 2.19.5
# Determines whether to keep the secrets required to encrypt within Ascender (important when backing up)
ascender_garbage_collect_secrets: false
# External PostgreSQL database name used for Ascender (this DB must exist)
ascender_replicas: 1
